var GlobValue = 
{
	EXPLOSIONPLAYER:1,
	EXPLOSIONENEMY:2,
	BULLETTOP:1,
	BULLETLEFT:2,
	COUNTNUMBER:[
	             "0.png",
	             "1.png",
	             "2.png",
	             "3.png",
	             "4.png",
	             "5.png",
	             "6.png",
	             "7.png",
	             "8.png",
	             "9.png"
	             ],
	 SCORE:0,
	 MEILI:0,
	 LIVIES:3,
	 NAME:"default"
}